permalink: /:year/:month/:day/:title.html
paginate: 10
#markdown: redcarpet

# 作者信息
author: 
  name: Woolaman 
  email: hxwang@iphy.me
  link: http://www.iphy.info
  github: http://github.com/woolaman

# 站点信息
title: 乌拉的博客
description: My personal blog
url: http://www.iphy.info

# gavatar头像及Favicon
gavatar: /public/img/cat2.png
favicon: /public/img/cat2.png

# google analytics 设置
#ga:
#id: UA-54262064-1 
#  url: painterlin.com

# disqus 设置
disqus:
  shortname: woolaman 

# 主题设置，自动激活某个 标签 or 目录?
#active: 新闻

# 首页除了最新文章外显示标签
cates:
  - 科研
  - 技术

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新
  archive: 归档

github:
  repo: woolaman.github.io
  branch: master


