# Site settings
title: www.iphy.info
email: hxwang@iphy.me

description: > # this means to ignore newlines until "baseurl:"
Science, Physics and Computer

#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://www.iphy.info" # the base hostname & protocol for your site
#twitter_username: ryanhxwang
#github_username:  iphys


# Build settings
markdown: kramdown


#site source, DIR is the directory 
#source: DIR

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

    scope:
      path: "projects"
      type: "pages" # 以前的 `page`， 在 Jekyll 2.2 里。
    values:
      layout: "project" # 覆盖之前的默认布局
      author: "Mr. Hyde"


