permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Hongxin Wang
  email: hxwang@iphy.me
  link: http://iphy.info
  github: http://github.com/iphys
  #weibo: http://weibo.com/orangeissweet
  #music: http://site.douban.com/linanya
  #linkedin: https://www.linkedin.com/pub/anya-lin/81/91/232

# 站点信息
title: 乌拉的博客
description: My personal blog
url: http://iphy.info
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
#ga:
#id: UA-54262064-1 
#  url: painterlin.com

# disqus 设置
disqus:
  shortname: iphy 

# 主题设置，自动激活某个 标签 or 目录?
active: 新闻

# 首页除了最新文章外显示标签
cates:
  - 科研
  - 技术

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新
  archive: 归档


