# Site settings
title: www.iphy.info
email: hxwang@iphy.me

description: Science, Physics and Computer
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://www.iphy.info" # the base hostname & protocol for your site

#twitter_username: ryanhxwang
#github_username:  iphys


# Build settings
markdown: kramdown


